name: "ocr_cls_postprocess"
backend: "python"
input [
  {
    name: "ocr_cls_post_in"
    data_type: TYPE_FP32
    dims: [ -1, 2 ]
  }
]

output [
  {
    name: "ocr_cls_post_out"
    data_type: TYPE_UINT8
    dims: [ -1 ]
  }
]

instance_group [
  {
      count: 1
      kind: KIND_CPU
  }
]
